import type { PlatformConfig } from "@/types/platform";

/** 默认 Claude 卡片的固定 ID */
export const DEFAULT_CLAUDE_ID = "00000000-0000-0000-0000-000000000000";

export interface PlatformPreset extends Omit<PlatformConfig, "id" | "order" | "enabled"> {
  apiKey?: string;
  /** 固定 ID（仅用于默认 Claude） */
  fixedId?: string;
}

/** 各预设平台可用模型列表 */
export const PRESET_MODELS: Record<string, string[]> = {
  "阿里百炼": ["qwen3.5-plus", "qwen3-max-2026-01-23", "qwen3-coder-next", "qwen3-coder-plus", "glm-5", "glm-4.7", "kimi-k2.5", "MiniMax-M2.5"],
  "MiniMax": ["MiniMax-M2.7", "MiniMax-M2.5"],
  "智谱": ["glm-5.1", "glm-5-turbo", "glm-5", "glm-4.7", "glm-4.5-air"],
  "Kimi": ["kimi-for-coding"],
  "火山方舟": ["doubao-seed-2.0-code", "doubao-seed-code", "kimi-k2.5", "glm-4.7", "deepseek-v3.2"],
  "腾讯混元": ["tc-code-latest", "hunyuan-2.0-instruct", "hunyuan-2.0-thinking", "hunyuan-t1", "hunyuan-turbos", "minimax-m2.5", "kimi-k2.5", "glm-5"],
  "小米Mimo": ["mimo-v2-pro"],
  "百度云": ["qianfan-code-latest"],
  "OpenRouter": ["anthropic/claude-sonnet-4.6", "anthropic/claude-opus-4.6", "minimax/minimax-m2.5"],
  "DeepSeek": ["deepseek-chat", "deepseek-reasoner"],
  "Ollama": ["qwen2.5-coder", "deepseek-coder-v2", "llama3.2", "qwen2.5", "codellama"],
};

export const PLATFORM_PRESETS: PlatformPreset[] = [
  {
    fixedId: DEFAULT_CLAUDE_ID,
    name: "Claude",
    icon: "anthropic.svg",
    baseUrl: "",
    defaultModel: "",
    models: "",
    defaultWorkDir: "",
    configDir: "",
    extraArgs: "",
  },
  {
    name: "阿里百炼",
    icon: "bailian.svg",
    baseUrl: "https://coding.dashscope.aliyuncs.com/apps/anthropic",
    defaultModel: "qwen3.5-plus",
    models: "qwen3.5-plus,qwen3-max-2026-01-23,qwen3-coder-next,qwen3-coder-plus,glm-5,glm-4.7,kimi-k2.5,MiniMax-M2.5",
    defaultWorkDir: "",
    configDir: "ali",
    extraArgs: "",
  },
  {
    name: "MiniMax",
    icon: "minimax.svg",
    baseUrl: "https://api.minimaxi.com/anthropic",
    defaultModel: "MiniMax-M2.7",
    models: "MiniMax-M2.7,MiniMax-M2.5",
    defaultWorkDir: "",
    configDir: "minimax",
    extraArgs: "",
  },
  {
    name: "智谱",
    icon: "zai.svg",
    baseUrl: "https://open.bigmodel.cn/api/anthropic",
    defaultModel: "glm-5.1",
    models: "glm-5.1,glm-5-turbo,glm-5,glm-4.7,glm-4.5-air",
    defaultWorkDir: "",
    configDir: "glm",
    extraArgs: "",
  },
  {
    name: "Kimi",
    icon: "kimi.svg",
    baseUrl: "https://api.kimi.com/coding/",
    defaultModel: "kimi-for-coding",
    models: "kimi-for-coding",
    defaultWorkDir: "",
    configDir: "kimi",
    extraArgs: "",
  },
  {
    name: "火山方舟",
    icon: "doubao.svg",
    baseUrl: "https://ark.cn-beijing.volces.com/api/coding",
    defaultModel: "doubao-seed-2.0-code",
    models: "doubao-seed-2.0-code,doubao-seed-code,kimi-k2.5,glm-4.7,deepseek-v3.2",
    defaultWorkDir: "",
    configDir: "volc",
    extraArgs: "",
  },
  {
    name: "腾讯混元",
    icon: "hunyuan.svg",
    baseUrl: "https://api.lkeap.cloud.tencent.com/coding/anthropic",
    defaultModel: "tc-code-latest",
    models: "tc-code-latest,hunyuan-2.0-instruct,hunyuan-2.0-thinking,hunyuan-t1,hunyuan-turbos,minimax-m2.5,kimi-k2.5,glm-5",
    defaultWorkDir: "",
    configDir: "tencent",
    extraArgs: "",
  },
  {
    name: "小米Mimo",
    icon: "xiaomimimo.svg",
    baseUrl: "https://api.xiaomimimo.com/anthropic",
    defaultModel: "mimo-v2-pro",
    models: "mimo-v2-pro",
    defaultWorkDir: "",
    configDir: "mimo",
    extraArgs: "",
  },
  {
    name: "百度云",
    icon: "baiducloud.svg",
    baseUrl: "https://qianfan.baidubce.com/anthropic/coding",
    defaultModel: "qianfan-code-latest",
    models: "qianfan-code-latest",
    defaultWorkDir: "",
    configDir: "baidu",
    extraArgs: "",
  },
  {
    name: "OpenRouter",
    icon: "openrouter.svg",
    baseUrl: "https://openrouter.ai/api",
    openaiBaseUrl: "https://openrouter.ai/api/v1",
    defaultModel: "anthropic/claude-sonnet-4.6",
    models: "anthropic/claude-sonnet-4.6,anthropic/claude-opus-4.6,minimax/minimax-m2.5",
    defaultWorkDir: "",
    configDir: "openrouter",
    extraArgs: "",
  },
  {
    name: "DeepSeek",
    icon: "deepseek.svg",
    baseUrl: "https://api.deepseek.com/anthropic",
    defaultModel: "deepseek-chat",
    models: "deepseek-chat,deepseek-reasoner",
    defaultWorkDir: "",
    configDir: "deepseek",
    extraArgs: "",
  },
  {
    name: "Ollama",
    icon: "ollama.svg",
    baseUrl: "http://localhost:11434",
    defaultModel: "qwen2.5-coder",
    models: "qwen2.5-coder,deepseek-coder-v2,llama3.2,qwen2.5,codellama",
    defaultWorkDir: "",
    configDir: "ollama",
    extraArgs: "",
  },
  {
    name: "OpenAI 兼容",
    icon: "default.svg",
    baseUrl: "",
    openaiBaseUrl: "https://api.openai.com/v1",
    anthropicCompatViaProxy: true,
    defaultModel: "",
    models: "",
    defaultWorkDir: "",
    configDir: "openai",
    extraArgs: "",
  },
  {
    name: "自定义",
    icon: "default.svg",
    baseUrl: "",
    defaultModel: "",
    models: "",
    defaultWorkDir: "",
    configDir: "",
    extraArgs: "",
  },
];
